export const colorThemes = [
  {
    name: "Leather Brown",
    value: "leather-brown",
    primary: "#8B4513",
    secondary: "#A0522D",
    accent: "#D2691E",
    light: "#DEB887",
  },
  {
    name: "Navy Blue",
    value: "navy-blue",
    primary: "#1e3a5f",
    secondary: "#2c5282",
    accent: "#3b82f6",
    light: "#60a5fa",
  },
  {
    name: "Forest Green",
    value: "forest-green",
    primary: "#2d5a3d",
    secondary: "#3d7a4d",
    accent: "#10b981",
    light: "#34d399",
  },
  {
    name: "Burgundy",
    value: "burgundy",
    primary: "#722f37",
    secondary: "#8b3a42",
    accent: "#dc2626",
    light: "#f87171",
  },
  {
    name: "Charcoal",
    value: "charcoal",
    primary: "#36454f",
    secondary: "#4a5c6a",
    accent: "#64748b",
    light: "#94a3b8",
  },
  {
    name: "Pastel Pink",
    value: "pastel-pink",
    primary: "#f8b4c4",
    secondary: "#fbbfd0",
    accent: "#ec4899",
    light: "#f9a8d4",
  },
  {
    name: "Pastel Blue",
    value: "pastel-blue",
    primary: "#a8d8ea",
    secondary: "#bde0f0",
    accent: "#0ea5e9",
    light: "#38bdf8",
  },
  {
    name: "Pastel Green",
    value: "pastel-green",
    primary: "#b8e0d2",
    secondary: "#c7e7dc",
    accent: "#14b8a6",
    light: "#2dd4bf",
  },
  {
    name: "Light Blue",
    value: "light-blue",
    primary: "#87CEEB",
    secondary: "#9dd9f3",
    accent: "#0284c7",
    light: "#0ea5e9",
  },
  {
    name: "Red",
    value: "red",
    primary: "#DC143C",
    secondary: "#e63950",
    accent: "#ef4444",
    light: "#f87171",
  },
  {
    name: "Green Yellow",
    value: "green-yellow",
    primary: "#ADFF2F",
    secondary: "#baff52",
    accent: "#84cc16",
    light: "#a3e635",
  },
  {
    name: "Silver",
    value: "silver",
    primary: "#C0C0C0",
    secondary: "#d0d0d0",
    accent: "#71717a",
    light: "#a1a1aa",
  },
  {
    name: "Deep Sea",
    value: "deep-sea",
    primary: "#01579B",
    secondary: "#0277bd",
    accent: "#0284c7",
    light: "#0ea5e9",
  },
  {
    name: "Purple Haze",
    value: "purple-haze",
    primary: "#7C3AED",
    secondary: "#8B5CF6",
    accent: "#A78BFA",
    light: "#C4B5FD",
  },
  {
    name: "Sunset Orange",
    value: "sunset-orange",
    primary: "#EA580C",
    secondary: "#F97316",
    accent: "#FB923C",
    light: "#FDBA74",
  },
  {
    name: "Emerald",
    value: "emerald",
    primary: "#059669",
    secondary: "#10B981",
    accent: "#34D399",
    light: "#6EE7B7",
  },
  {
    name: "Rose Gold",
    value: "rose-gold",
    primary: "#BE185D",
    secondary: "#E11D48",
    accent: "#FB7185",
    light: "#FDA4AF",
  },
  {
    name: "Teal",
    value: "teal",
    primary: "#0F766E",
    secondary: "#14B8A6",
    accent: "#2DD4BF",
    light: "#5EEAD4",
  },
  {
    name: "Indigo",
    value: "indigo",
    primary: "#4338CA",
    secondary: "#6366F1",
    accent: "#818CF8",
    light: "#A5B4FC",
  },
  {
    name: "Amber",
    value: "amber",
    primary: "#D97706",
    secondary: "#F59E0B",
    accent: "#FBBF24",
    light: "#FCD34D",
  },
  {
    name: "Cyan",
    value: "cyan",
    primary: "#0891B2",
    secondary: "#06B6D4",
    accent: "#22D3EE",
    light: "#67E8F9",
  },
  {
    name: "Violet",
    value: "violet",
    primary: "#6D28D9",
    secondary: "#7C3AED",
    accent: "#A78BFA",
    light: "#C4B5FD",
  },
  {
    name: "Coral",
    value: "coral",
    primary: "#F43F5E",
    secondary: "#FB7185",
    accent: "#FDA4AF",
    light: "#FECDD3",
  },
];

export type ColorTheme = typeof colorThemes[number];
