"use client"

import {
  BookOpen,
  Users,
  FileText,
  LayoutDashboard,
  Code,
  Calendar,
  Brain,
  CalendarDays,
  PenTool,
  Music,
  Blocks,
  Pencil,
  FolderKanban,
  LayoutGrid,
  BookText,
  Film,
  Type,
  Workflow,
  Image as ImageIcon,
  Video,
  Link,
  GraduationCap,
  Layers,
  PenLine,
  ChefHat,
  Wallet,
  Plane,
  CheckSquare,
  Mic,
  Target,
  Dumbbell,
  DollarSign,
  ShoppingCart,
  MessageSquare,
  Bell,
  Languages,
  Search,
  UtensilsCrossed,
  Trophy,
  StickyNote,
  GitBranch,
  Zap,
} from "lucide-react"

export const BUILTIN_NOTEBOOK_TEMPLATES = [
  { id: "simple", name: "Simple Notebook", icon: BookOpen, color: "from-amber-500 to-orange-500" },
  { id: "meeting-notes", name: "Meeting Notes", icon: Users, color: "from-emerald-500 to-teal-500" },
  { id: "document", name: "Document", icon: FileText, color: "from-blue-500 to-cyan-500" },
  { id: "dashboard", name: "Dashboard", icon: LayoutDashboard, color: "from-purple-500 to-pink-500" },
  { id: "code-notebook", name: "Code Notebook", icon: Code, color: "from-slate-600 to-slate-800" },
  { id: "planner", name: "Planner", icon: Calendar, color: "from-orange-500 to-red-500" },
  { id: "ai-research", name: "AI Research", icon: Brain, color: "from-rose-500 to-pink-500" },
  { id: "diary", name: "Diary", icon: CalendarDays, color: "from-pink-500 to-rose-500" },
  { id: "journal", name: "Journal", icon: PenTool, color: "from-stone-500 to-stone-700" },
  { id: "piano-notes", name: "Piano Notes", icon: Music, color: "from-slate-500 to-slate-700" },
  { id: "vocabulary", name: "Vocabulary", icon: BookOpen, color: "from-indigo-500 to-purple-600" },
  { id: "custom", name: "Custom Page", icon: Blocks, color: "from-indigo-500 to-violet-500" },
  { id: "doodle", name: "Doodle Pad", icon: Pencil, color: "from-cyan-500 to-blue-500" },
  { id: "project", name: "Project Hub", icon: FolderKanban, color: "from-indigo-500 to-purple-600" },
  { id: "loop", name: "Loop Workspace", icon: LayoutGrid, color: "from-purple-500 to-pink-500" },
  { id: "story", name: "Story Workshop", icon: BookText, color: "from-amber-500 to-orange-600" },
  { id: "storytelling", name: "Storytelling Studio", icon: Film, color: "from-purple-500 via-pink-500 to-orange-500" },
  { id: "typewriter", name: "TypeWriter", icon: Type, color: "from-blue-500 via-purple-500 to-pink-600" },
  { id: "n8n", name: "n8n Workflows", icon: Workflow, color: "from-blue-500 via-indigo-500 to-purple-600" },
  { id: "image-prompt", name: "Image Prompts", icon: ImageIcon, color: "from-pink-500 via-purple-500 to-indigo-600" },
  { id: "video-prompt", name: "Video Prompts", icon: Video, color: "from-blue-500 via-cyan-500 to-teal-600" },
  { id: "link", name: "Link Manager", icon: Link, color: "from-indigo-500 via-purple-500 to-pink-600" },
  { id: "studybook", name: "Study Book", icon: GraduationCap, color: "from-blue-500 to-indigo-600" },
  { id: "flashcard", name: "Flashcards", icon: Layers, color: "from-violet-500 to-purple-600" },
  { id: "whiteboard", name: "Whiteboard", icon: PenLine, color: "from-sky-500 to-blue-600" },
  { id: "recipe", name: "Recipe Book", icon: ChefHat, color: "from-orange-500 to-red-600" },
  { id: "expense", name: "Expense Manager", icon: Wallet, color: "from-emerald-500 to-teal-600" },
  { id: "trip", name: "Trip Planner", icon: Plane, color: "from-sky-500 to-blue-600" },
  { id: "todo", name: "Advanced To-Do", icon: CheckSquare, color: "from-indigo-500 to-purple-600" },
  { id: "sound-box", name: "Sound Box", icon: Mic, color: "from-indigo-500 to-purple-500" },
  { id: "book-notes", name: "Book Reading Notes", icon: BookOpen, color: "from-amber-500 to-orange-500" },
  { id: "habit-tracker", name: "Habit Tracker", icon: Target, color: "from-emerald-500 to-teal-500" },
  { id: "workout-log", name: "Workout Log", icon: Dumbbell, color: "from-orange-500 to-red-500" },
  { id: "budget-planner", name: "Budget Planner", icon: DollarSign, color: "from-blue-500 to-cyan-500" },
  { id: "class-notes", name: "Class Notes", icon: GraduationCap, color: "from-purple-500 to-pink-500" },
  { id: "research-builder", name: "Research Builder", icon: Brain, color: "from-violet-500 to-purple-600" },
  { id: "grocery-list", name: "Grocery List", icon: ShoppingCart, color: "from-green-500 to-emerald-500" },
  { id: "expense-sharer", name: "Expense Sharer", icon: Users, color: "from-teal-500 to-cyan-500" },
  { id: "project-pipeline", name: "Project Pipeline", icon: Workflow, color: "from-cyan-500 to-blue-500" },
  { id: "prompt-diary", name: "Prompt Diary", icon: MessageSquare, color: "from-indigo-500 to-purple-500" },
  { id: "save-the-date", name: "Save the Date", icon: Bell, color: "from-rose-500 to-pink-500" },
  { id: "important-urls", name: "Important URLs", icon: Link, color: "from-red-500 to-pink-500" },
  { id: "language-translator", name: "Language Translator", icon: Languages, color: "from-sky-500 to-blue-500" },
  { id: "dictionary", name: "Dictionary", icon: Search, color: "from-slate-500 to-gray-500" },
  { id: "meals-planner", name: "Meals Planner", icon: UtensilsCrossed, color: "from-orange-500 to-amber-500" },
  { id: "games-scorecard", name: "Games Scorecard", icon: Trophy, color: "from-yellow-500 to-amber-500" },
  { id: "sticker-book", name: "Sticker Book", icon: StickyNote, color: "from-lime-500 to-green-500" },
  { id: "mind-map", name: "Mind Map", icon: GitBranch, color: "from-violet-500 to-purple-600" },
  { id: "goal-tracker", name: "Goal Tracker", icon: Target, color: "from-blue-500 to-indigo-600" },
  { id: "ai-prompt-studio", name: "AI Prompt Studio", icon: Zap, color: "from-yellow-500 to-orange-600" },
  { id: "tutorial-learn", name: "Tutorial Learn", icon: GraduationCap, color: "from-indigo-500 to-blue-600" },
] as const

export type BuiltinNotebookTemplate = (typeof BUILTIN_NOTEBOOK_TEMPLATES)[number]

