export const BUILTIN_NOTEBOOK_TEMPLATE_IDS = [
  "simple",
  "meeting-notes",
  "document",
  "dashboard",
  "code-notebook",
  "planner",
  "ai-research",
  "diary",
  "journal",
  "piano-notes",
  "vocabulary",
  "custom",
  "doodle",
  "project",
  "loop",
  "story",
  "storytelling",
  "typewriter",
  "n8n",
  "image-prompt",
  "video-prompt",
  "link",
  "studybook",
  "flashcard",
  "whiteboard",
  "recipe",
  "expense",
  "trip",
  "todo",
  "sound-box",
  "book-notes",
  "habit-tracker",
  "workout-log",
  "budget-planner",
  "class-notes",
  "research-builder",
  "grocery-list",
  "expense-sharer",
  "project-pipeline",
  "prompt-diary",
  "save-the-date",
  "important-urls",
  "language-translator",
  "dictionary",
  "meals-planner",
  "games-scorecard",
  "sticker-book",
  "mind-map",
  "goal-tracker",
  "ai-prompt-studio",
  "tutorial-learn",
] as const

export type BuiltinNotebookTemplateId =
  (typeof BUILTIN_NOTEBOOK_TEMPLATE_IDS)[number]

